version: "2"
services:
  server:
    container_name: parkly_server
    build:
      context: ./server
    volumes:
      - ./server:/server
      - ./backups:/backups
    depends_on:
      - mongodb
    ports:
      - 4000:4000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3000:3000
